pool:
  vmImage: ubuntu-latest

variables:
  acrserviceconnection: 'Acr_connection'
  frontendrepository: 'credpay/frontend'
  userrepository: 'credpay/user-service'
  paymentrepository: 'credpay/payment-service'
  tag: '$(Build.BuildId)'

stages:
  - stage: dockerbuild
    displayName: Docker Build

    jobs:
      - job: buildpushImages
        displayName: Build and Push Docker Images

        steps:
          - checkout: self

          - task: Docker@2
            displayName: Build and Push Frontend Image
            inputs:
              containerRegistry: '$(acrserviceconnection)'
              repository: '$(frontendrepository)'
              command: 'buildAndPush'
              Dockerfile: 'frontend-react/dockerfile'
              buildContext: 'frontend-react'
              tags: |
                $(tag)
                latest