stages:
- stage: terraform
  displayName: Terraform Infra

  jobs:
  - job: terraformapply
    displayName: Terraform Init & Apply

    steps:
    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/terraform'
        commandOptions: '-reconfigure'
        backendServiceArm: 'Azure subscription 1(3216be10-695a-4fd6-ae65-70140df12a16)'
        backendAzureRmOverrideSubscriptionID: '3216be10-695a-4fd6-ae65-70140df12a16'
        backendAzureRmResourceGroupName: 'Capstone-rg'
        backendAzureRmStorageAccountName: 'credpyproject'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'credpyproject.terraform.tfstate'

    - task: AzureCLI@3
      inputs:
        connectionType: 'azureRM'
        azureSubscription: 'Azure subscription 1(3216be10-695a-4fd6-ae65-70140df12a16)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform init
          terraform apply -auto-approve
