FROM python:3.14-slim AS build
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
ENV DB_USERNAME=postgres \
    DB_HOST=Localhost \
    DB_PORT=5432 \
    DB_NAME=credpay
EXPOSE 5000
ENTRYPOINT ["Uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]

     
